config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get "/users/sign_up",  :to => "home#index"
  end
  devise_for :users

  root to: "home#index"

  resources :members
  resources :blogs
  resources :board_members
  resources :announcements, only: :index
  resources :events, only: :index

  get '/strategic_plan', to: 'strategic_plans#show', as: 'strategic_plan'
  get '/Strategic_Plan', to: 'strategic_plans#show'
  resources :strategic_plans, only: [:edit, :update]

  # Routes used by member registration pages
  get 'registration', to: "registration#index", as: "registration"
  get 'registration/success', to: 'registration#success', as: 'success'
  get '/discounted_membership', to: "registration#discounted_membership", as: 'discounted_membership'
  get 'discounted_membership/about', to: "registration#about_discounted_membership", as: 'about_discounted_membership'
  get 'member_search', to: "member_search#index", as: "member_search"
  get "member_search/results", to: "member_search#show", as: "member_search_results"
  mount Members::API => '/api/members'

  # Admin routes
  get "/admin/menu", to: "admin#index", as: "admin"
  put "admin/update_settings", to: "admin#update_settings", as: 'update_settings'

  # Webhook to accept transaction updates from PayPal
  post '/payment_webhook', to: 'webhooks#create', as: 'payment_webhook'

  namespace :v1 do
    resources :events, only: [:index]
  end

end

app/views/admin/index.html.erb
<div class="container text-center">
  <h3 class="header center light">Admin Menu</h3>
</div>

<div class="section" id="admin-nav">
  <div class="row text-center">
    <div class="col s12 m4 center">
      <div class="icon-block">
        <h2 class="center"><i class="material-icons">person_add</i></h2>
        <h5 class="center">Members</h5>
        <%= link_to "Add new member", new_member_path, class: "btn waves-effect waves-light" %>
        <br><br>
        <%= link_to "Current Members", members_path, class: "btn waves-effect waves-light" %>
      </div>
    </div>

    <div class="col s12 m4 center">
      <div class="icon-block">
        <h2 class="center"><i class="material-icons">rss_feed</i></h2>
        <h5 class="center">Blog</h5>
        <%= link_to "Add New Blog Post", new_blog_path, class: "btn waves-effect waves-light" %>
        <br><br>
        <%= link_to "Update Blog Posts", blogs_path, class: "btn waves-effect waves-light" %>
      </div>
    </div>

    <div class="col s12 m4 center">
      <div class="icon-block">
        <h2 class="center"><i class="material-icons">group</i></h2>
        <h5 class="center">Board Members</h5>
        <%= link_to "Add Board Member", new_board_member_path, class: "btn waves-effect waves-light" %>
        <br><br>
        <%= link_to "Update Board Members", board_members_path, class: "btn waves-effect waves-light" %>
      </div>
    </div>

    <div class="col s12 m4 center">
      <div class="icon-block">
        <h2 class="center"><i class="material-icons">list</i></h2>
        <h5 class="center">Strategic Plan</h5>
        <%= link_to "Update Strategic Plan", edit_strategic_plan_path(StrategicPlan.first), class: "btn waves-effect waves-light" %>
      </div>
    </div>
  </div>
</div>

<div class='container center'>
  <% if @offering_discounted_membership %>
    <h5 class='header light'>The discounted membership renewal page is currently live. Anyone with the link can access the page at <%= link_to "https://eatrightatlanta.org/discounted_membership", discounted_membership_path, class: 'red-text', target: :_blank %>.</h5>
    <h6><%= link_to "Turn off discounted membership page", update_settings_path, class: "btn waves-effect waves-light hoverable btn-large red", method: :put %>
      or <%= link_to "Learn More", about_discounted_membership_path, class: 'header purple-text' %>
    </h6>
  <% else %>
    <h5 class='header light'>Is it getting toward the end of the membership year? Has the board decided to offer a membership discount for the remainder of the membership year?</h5>
    <h6><%= link_to "Turn on discounted membership page", update_settings_path, class: 'btn waves-effect waves-light hoverable btn-large green', method: :put %>
      or <%= link_to "Learn More", about_discounted_membership_path, class: 'header purple-text' %>
    </h6>
  <% end %>
</div>