config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get "/users/sign_up",  :to => "home#index"
  end
  devise_for :users

  root to: "home#index"

  resources :members
  resources :blogs
  resources :board_members
  resources :announcements, only: :index
  resources :events, only: :index

  get '/strategic_plan', to: 'strategic_plans#show', as: 'strategic_plan'
  get '/Strategic_Plan', to: 'strategic_plans#show'
  resources :strategic_plans, only: [:edit, :update]

  # Routes used by member registration pages
  get 'registration', to: "registration#index", as: "registration"
  get 'registration/success', to: 'registration#success', as: 'success'
  get '/discounted_membership', to: "registration#discounted_membership", as: 'discounted_membership'
  get 'discounted_membership/about', to: "registration#about_discounted_membership", as: 'about_discounted_membership'
  get 'member_search', to: "member_search#index", as: "member_search"
  get "member_search/results", to: "member_search#show", as: "member_search_results"
  mount Members::API => '/api/members'

  # Admin routes
  get "/admin/menu", to: "admin#index", as: "admin"
  put "admin/update_settings", to: "admin#update_settings", as: 'update_settings'

  # Webhook to accept transaction updates from PayPal
  post '/payment_webhook', to: 'webhooks#create', as: 'payment_webhook'

  namespace :v1 do
    resources :events, only: [:index]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
  render "home"
end

end

app/views/home/home.html.erb
<div id="fb-root"></div>
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br>
    <h1 class="header center orange-text">Greater Atlanta Dietetic Association</h1>
    <div class="row center">
      <h5 class="header col s12 light">Join today to weigh in on nutrition.</h5>
    </div>
    <div class="row center" data-turbolinks="false">
      <%= link_to "Join or Renew", registration_path, class: "btn-large waves-effect waves-light orange hoverable home-page-join-gada-button" %>
      <%= link_to "Check Membership Status", member_search_path, class: "btn-large waves-effect waves-light orange hoverable" %>
    </div>
    <%= render partial: "/donate" %>
    <br><br>
  </div>

  <div>
    <div class="home-main">
      <div class="fb-page row-item" data-href="https://www.facebook.com/eatrightatl" data-tabs="timeline" data-small-header="false" data-width="500" data-height="800" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/eatrightatl" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/eatrightatl">GADA (Greater Atlanta Dietetic Association)</a></blockquote>
      </div>

      <div class='row-item'>
        <h5 class='header light'>The Greater Atlanta Dietetic Association (GADA) is the professional association for dietitians and nutrition professionals in the metropolitan Atlanta area. RDNs and students join GADA to network, participate in leadership and professional growth, and earn continuing education hours. GADA empowers its members to be the local food and nutrition experts by providing networking, volunteering, and professional development opportunities.</h5>
        <br><br>
        <%= link_to "View GADA's Strategic Plan", strategic_plan_path, class: "btn-large waves-effect waves-light orange hoverable" %>
        <br><br>
        <h6 class='counties-served-message'>Counties GADA serves: Butts, Carroll, Clayton, Cobb, Coweta, DeKalb, Douglas, Fayette, Fulton, Gwinnett, Haralson, Heard, Henry, Newton, Paulding, Rockdale, Spalding</h6>
      </div>

    </div>
  </div>
  <br><br>
  <div class="container">
    <div class="section">
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h5 class="center header teal-text">Mission</h5>
            <p class="light">Empower GADA members to be the local food and nutrition experts by providing networking and professional development opportunities.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h5 class="center header teal-text">Vision</h5>
            <p class="light">Optimize Atlanta area dietitians’ impact on the public through advocacy, education, and volunteerism.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h5 class="center header teal-text">Values</h5>
            <ol>
              <li class="light">Customer Focus: Meet the needs and exceed the expectations of internal and external customers.</li>
              <li class="light">Integrity: Act ethically with accountability for life-long learning and commitment to excellence.</li>
              <li class="light">Social Responsibility: Make decisions with consideration for inclusivity as well as environmental, economic and social implications.</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>