config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get "/users/sign_up",  :to => "home#index"
  end
  devise_for :users

  root to: "home#index"

  resources :members
  resources :blogs
  resources :board_members
  resources :announcements, only: :index
  resources :events, only: :index

  get '/strategic_plan', to: 'strategic_plans#show', as: 'strategic_plan'
  get '/Strategic_Plan', to: 'strategic_plans#show'
  resources :strategic_plans, only: [:edit, :update]

  # Routes used by member registration pages
  get 'registration', to: "registration#index", as: "registration"
  get 'registration/success', to: 'registration#success', as: 'success'
  get '/discounted_membership', to: "registration#discounted_membership", as: 'discounted_membership'
  get 'discounted_membership/about', to: "registration#about_discounted_membership", as: 'about_discounted_membership'
  get 'member_search', to: "member_search#index", as: "member_search"
  get "member_search/results", to: "member_search#show", as: "member_search_results"
  mount Members::API => '/api/members'

  # Admin routes
  get "/admin/menu", to: "admin#index", as: "admin"
  put "admin/update_settings", to: "admin#update_settings", as: 'update_settings'

  # Webhook to accept transaction updates from PayPal
  post '/payment_webhook', to: 'webhooks#create', as: 'payment_webhook'

  namespace :v1 do
    resources :events, only: [:index]
  end

end

app/models/board_member.rb
class BoardMember < ApplicationRecord
end

app/controllers/board_members_controller.rb
class BoardMembersController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  load_and_authorize_resource  only: [:new, :create, :edit, :update, :destroy]

  def index
    @board_members = BoardMember.all.order(:order)
  end

  def new
    @board_member = BoardMember.new
  end

  def create
    @board_member = BoardMember.new(board_member_params)
    respond_to do |format|
      if @board_member.save
        format.html { redirect_to "/board_members", notice: "Board member #{@board_member.name} was successfully created." }
      else
        format.html { render :new, alert: "Error adding board member. Make sure all required fields are correctly completed and try again." }
      end
    end
  end

  def edit
    @board_member = BoardMember.find(params[:id])
  end

  def update
    @board_member = BoardMember.find(params[:id])
    respond_to do |format|
      if @board_member.update(board_member_params)
        format.html { redirect_to "/board_members", notice: "Board member info was successfully updated." }
        format.json { render :show, status: :created, location: @board_member }
      else
        format.html { redirect_to "/board_members/#{@board_member.id}/edit", alert: "Error updating board member. Make sure all required fields are correctly completed and try again." }
      end
    end
  end

  def destroy
    @board_member = BoardMember.find(params[:id])
    if @board_member.delete
       redirect_to board_members_path,
                  notice: 'Board member successfully deleted.'
    else
      redirect_to board_members_path,
                  alert: 'Error deleting board member.'
    end
  end

  private
  def board_member_params
    params.require(:board_member)
      .permit(:name, :position, :email, :description, :photo)
  end

end

app/views/board_members/_form.html.erb
<div class='form-container z-depth-3'>
  <%= form_for @board_member, :url =>"/board_members/#{@board_member.id}" do |f| %>
    <div class='form'>
      <div class='input-field'>
        <%= f.label :name, "Name", :class => "form-label" %>
        <%= f.text_field :name, :class => "validate", required: true %>
      </div>
      <div class='input-field'>
        <%= f.label :position, "Board Position", :class => "form-label" %>
        <%= f.text_field :position, :class => "validate", required: true %>
      </div>
      <div class='input-field'>
        <%= f.label :email, "GADA Email Address (optional)", :class => "form-label" %>
        <%= f.text_field :email, :class => "validate" %>
      </div>
      <div class='input-field'>
        <%= f.label :description, "Description", :class => "form-label" %>
        <%= f.text_area :description, :class => "materialize-textarea validate", required: true %>
      </div>
      <div class='input-field'>
        <%= f.label :photo, "Photo URL (a direct https link to a hosted image. ex: https://i.imgur.com/nLJvnz4.png)", :class => "form-label" %>
        <%= f.text_field :photo, :class => "validate", required: true %>
      </div>

      <div class='form_button_container'>
        <%= f.submit "Submit", :class => 'waves-effect waves-light btn-large hoverable' %>
        <%= link_to "Nevermind", admin_path, :class => 'waves-effect waves-light btn-large deep-orange hoverable' %>
      </div>
    </div>
  <% end %>
</div>

app/views/board_members/edit.html.erb
<div class="container center">
  <h3 class="header center light orange-text">Update Board Member Information</h3>
  <%= render partial: 'form' %>
</div>

app/views/board_members/index.html.erb
<h2 class="header center orange-text">Meet Your GADA Board of Directors</h2>



<div class="cards-container">
  <% @board_members.each do |board_member| %>
    <div class="card hoverable" id="board_member_card">
      <div class="card-image">
        <%= image_tag("#{board_member.photo}", class: "board-member-photo activator") %>
      </div>
      <div class="card-content">
        <span class="activator teal-text board-member-name"><%= board_member.name %><i class="material-icons right">more_vert</i></span>
        <h6 class="header light"><%= board_member.position %></h6>
        <% if board_member.email %>
          <h6 class="header light"><%= link_to board_member.email, "mailto:#{board_member.email}", :class => 'deep-orange-text' %></h6>
        <% end %>
      </div>
      <div class="card-reveal">
        <span class="board-member-name teal-text card-title"><%= board_member.name %><i class="material-icons right">close</i></span>
        <h6 class="header light"><%= board_member.position %></h6>
        <h6 class="header light"><%= board_member.email %></h6>
        <h6><%= simple_format(board_member.description) %></h6>
      </div>
      <% if user_signed_in? %>
        <div class="right">
          <%= link_to("/board_members/#{board_member.id}/edit") do %>
            <i class="material-icons">edit</i>
          <% end %>
          <%= link_to("/board_members/#{board_member.id}", method: :delete, data: {confirm: "Are you sure you want to delete this board member?"}) do %>
            <i class="material-icons deep-orange-text">delete</i>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/board_members/new.html.erb
<div class="container center">
  <h3 class="header center light orange-text">Add a New Board Member</h3>
  <%= render partial: 'form' %>
</div>