config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get "/users/sign_up",  :to => "home#index"
  end
  devise_for :users

  root to: "home#index"

  resources :members
  resources :blogs
  resources :board_members
  resources :announcements, only: :index
  resources :events, only: :index

  get '/strategic_plan', to: 'strategic_plans#show', as: 'strategic_plan'
  get '/Strategic_Plan', to: 'strategic_plans#show'
  resources :strategic_plans, only: [:edit, :update]

  # Routes used by member registration pages
  get 'registration', to: "registration#index", as: "registration"
  get 'registration/success', to: 'registration#success', as: 'success'
  get '/discounted_membership', to: "registration#discounted_membership", as: 'discounted_membership'
  get 'discounted_membership/about', to: "registration#about_discounted_membership", as: 'about_discounted_membership'
  get 'member_search', to: "member_search#index", as: "member_search"
  get "member_search/results", to: "member_search#show", as: "member_search_results"
  mount Members::API => '/api/members'

  # Admin routes
  get "/admin/menu", to: "admin#index", as: "admin"
  put "admin/update_settings", to: "admin#update_settings", as: 'update_settings'

  # Webhook to accept transaction updates from PayPal
  post '/payment_webhook', to: 'webhooks#create', as: 'payment_webhook'

  namespace :v1 do
    resources :events, only: [:index]
  end

end

app/controllers/member_search_controller.rb
class MemberSearchController < ApplicationController

  def index
    if params["/member_search/results"]
      email = member_params["email"].downcase
      @member = Member.find_by(email: email)
      now = Date.today
      if @member
        @expiration_date = @member.membership_expiration_date.strftime("%D")
        if @member.membership_expiration_date >= now
          @message = "Your membership is current through #{@expiration_date}"
        else
          @message = "Your membership expired on #{@expiration_date}"
        end
      else
        @message = "The email address #{email} is not associated with a current member"
      end
    end
  end



  private

  def member_params
    params.require("/member_search/results").permit("email")
  end
end

app/views/member_search/index.html.erb
<div class="container center">
  <h4 class="header col s12 light">Look up your membership using your email address</h4>

  <h5 class="header col s12">The GADA membership year runs from <b class='teal-text'>June 1 through May 31</b> annually</h5>

  <h5 class="header col s12 light blue-text">If you joined online using PayPal, your membership email may be the one you use to log in to PayPal. If you prefer we contact you at a different email address, <b><a href="mailto:gadainfo@eatrightatlanta.org">let us know</a></b>.</h5>

  <h4 class="header center deep-orange-text light"><%= @message %></h4>

  <div class="form-container z-depth-3">
    <%= form_for member_search_results_path, method: :get do |f| %>
      <div class="input-field">
        <%= f.label :email, "Email address" %>
        <%= f.text_field :email, :class => "validate", required: true %>
      </div>
      <%= f.submit "Find", class: "btn waves-effect waves-light"%>
    <% end %>
  </div>

  <h5 class="header col s12 light red-text">If you joined or renewed recently, it may take a few days for your membership status to be updated in our records. Don't hesitate to <b><a href="mailto:gadainfo@eatrightatlanta.org" class='red-text'>email us</a></b> with any membership related concerns.</h5>
  <br><br>
  <span data-turbolinks="false"><%= link_to "Join or Renew", registration_path, class: "btn-large waves-effect waves-light green darken-1" %></span>

</div>